name: Merge and Commit Tiles
on: [workflow_dispatch, push]

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick

    - name: Create output directory
      run: mkdir -p Merged/Regular

    - name: Merge images with scaling
      run: |
        FRONT="Export/Regular/Front.png"
        BACK="Export/Regular/Back.png"
        FRONT_SIZE=$(identify -format "%wx%h" "$FRONT")

            # Copy Front and Back directly
        mkdir -p Merged/Regular
        cp "$FRONT" "Merged/Regular/Front.png"
        cp "$BACK" "Merged/Regular/Back.png"
    
        for image in Export/Regular/*.png; do
          filename=$(basename "$image")
          [[ "$filename" == @(Front|Back).png ]] && continue
      
          convert "$image" -resize "90%" -background none -gravity center -extent "$FRONT_SIZE" \
            "$FRONT" +swap -composite "Merged/Regular/$filename"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Merged/Regular
        git commit -m "Auto-merged tiles (scaled 90%)"
        git push origin 
