name: Merge and Commit Tiles
on: [workflow_dispatch, push]

jobs:
  merge-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick

    - name: Create output directory
      run: mkdir -p Merged/Regular

    - name: Merge images with scaling
      run: |
        FRONT="Export/Regular/Front.png"
        # Get background dimensions
        FRONT_SIZE=$(identify -format "%wx%h" "$FRONT")
        SCALE="90%"
        
        for image in Export/Regular/*.png; do
          filename=$(basename "$image")
          [[ "$filename" == "Back.png" || "$filename" == "Blank.png" ]] && continue
          
          # Scale overlay to 90% of background size and center
          composite -gravity center \
            \( "$image" -resize "$SCALE" -background none -extent "$FRONT_SIZE" \) \
            "$FRONT" \
            "Merged/Regular/$filename"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Merged/Regular
        git commit -m "Auto-merged tiles (scaled 90%)"
        git push origin 
